zh-cn:
  languageName: "中文"
  languageCode: "zh-Hans-CN"
  contentDir: "content/zh-cn"
  weight: 1
  menus:
    main:
      - name: "首页"
        url: "/"
        identifier: "home"
        weight: 100
      - name: "文章"
        url: "/posts/"
        identifier: "posts"
        weight: 200
      - name: "开源项目"
        url: "/portfolio/"
        identifier: "portfolio"
        weight: 300
      - name: "关于"
        url: "/about/"
        identifier: "about"
        weight: 400
